version: '3.8'
services:
  web-customer-vnselly:
    image: web-customer-vnselly
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:80
    networks:
      - overlay
networks:
  overlay:
